### ISSUE TITLE
ヘッダーの項目でリンク先がまだ用意できていないものは、リンクの機能を無効化（disable）したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#16]
## 対象
プロポーザル、スポンサー、チケット、レビュアー の項目

## 現状
ブラウザの別タブでティザーが開く

## 要望
リンクの機能を無効化（disable）したい。
リンクはクリックできない状態（必須ではないですが、ホバーすると「準備中」というツールチップが出たら分かりやすいと思います）

※Issue作成時点でnikkieのIMOなので、やらないもしくは無効化とは別の対応になる可能性もあります。
着手するスタッフの方は、Slackを確認してください
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1616338475047800

**Comment by papi-tokei** [comment]
修正済みです。
マスターマージ後にクローズ予定です。

**Comment by papi-tokei** [comment]
@ftnext 
マスターにマージ済みです。
修正内容が問題なければ、このissueのクローズをお願いします。

**Comment by ftnext** [comment]
確認しました。
想定していた通りです。
対応ありがとうございます
