### ISSUE TITLE
ヘッダーの NEWS のリンク先を pyconjp2021 ラベルのブログ記事一覧にしたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#17]
## 現状
ヘッダーのNEWSは https://pyconjp.blogspot.com/2021/ へのリンクになっている。
2021年に公開された記事一覧と認識しています

## 要望
https://pyconjp.blogspot.com/search/label/pyconjp2021 にリンクを差し替えたい。
これは「pyconjp2021」というラベルが付いた記事の一覧

2021年に公開された記事一覧では、pyconjptvやAssociation運営会議の記事など、PyCon JP 2021に興味のある人にとってはノイズの記事が混じるため

**Comment by papi-tokei** [comment]
修正済みです。
マスターマージ後にクローズ予定です。

**Comment by papi-tokei** [comment]
@ftnext 
マスターにマージ済みです。
修正内容が問題なければ、このissueのクローズをお願いします。

**Comment by ftnext** [comment]
確認しました。
対応ありがとうございました
