### ISSUE TITLE
表記修正: 開催予定日時 → 開催予定日

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#24]
時間は示していないので、「開催予定日」の方が合っているなと思いました。
急いでいない（MUSTではなくIMO）ので、公開後の対応でもかまいません

該当箇所
https://github.com/pyconjp/pycon.jp.2021.teaser/blob/7b145baf7308377e76094b6656b34555ba28139a/components/Domains/TopContent/index.vue#L53

**Comment by papi-tokei** [comment]
@ftnext 
try46さんの方で修正頂いたものをmasterにマージ済みです。
問題なければクローズお願いします。

**Comment by ftnext** [comment]
@try46 ありがとうございます。
確認しました
