### ISSUE TITLE
フッターの文言を更新したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#25]
Slackの以下で話していた件です。
https://pyconjp.slack.com/archives/C01FBPX83GD/p1616337504029500
現状よりはカイゼンされると思うので、MUSTとしてリリース前に反映したい考えです（が、作業時間の捻出もあると思うので、担当の方は相談してください）

該当箇所
https://github.com/pyconjp/pycon.jp.2021.teaser/blob/7b145baf7308377e76094b6656b34555ba28139a/components/Domains/Footer/index.vue#L21

## 暫定的な文言案（細かい部分は変えてもらって大丈夫です）

PyCon JP 2021 in Tokyo is produced by the [PyCon JP Association](https://www.pycon.jp/committee/english.html).
For the latest information and contact information for PyCon JP 2021, please visit [our blog](https://pyconjp.blogspot.com/).

**Comment by papi-tokei** [comment]
@ftnext 
修正しました。
masterまでマージ済みです。
問題なければクローズして頂ければと思います。

**Comment by ftnext** [comment]
確認しました。
対応ありがとうございます
