### ISSUE TITLE
日程まわりで「仮」を表す文言を削って、日程が確定したことを示したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#36]
ref: https://pyconjp.slack.com/archives/C01FBPX83GD/p1619109211182100

## 現在

```
Conference: Oct.15(Fri)- 16(Sat), 2021 (tentative)
開催予定日 : 2021年10月15日(金) - 16日(土) 
```

- tentative をトル
- 開催~予定~日

## 変更後

```
Conference: Oct.15(Fri)- 16(Sat), 2021
開催日 : 2021年10月15日(金) - 16日(土) 
```

日程に関して上記以外にも「仮」を意味する表現があったら、合わせて削ってほしいです

**Comment by papi-tokei** [comment]
@ftnext @yuukinetwork 
修正を確認、マージ済みです。
確認が遅くなってすみません。

**Comment by ftnext** [comment]
対応ありがとうございました。
反映されたことを確認しました
https://2021.pycon.jp/
