### ISSUE TITLE
お問い合わせメールアドレスを掲載したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#39]
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1620317534118700 で頭出しした件

https://pycon.jp/2020/ のフッターにあるように

- お問い合わせメールアドレス（2020と同じでOK）
- 案内文言（日・英）
  - FAQはないので、FAQの文は削除
  - FAQ以外の文について、2020をベースに用意

を記載したいです。

記載位置についてはこれ！というアイデアはなく、フッターかなあと思っています

**Comment by k-nakamura** [comment]
masterへのプルリクエストを作成しました。
https://github.com/pyconjp/pycon.jp.2021.teaser/pull/59

**Comment by papi-tokei** [comment]
@ftnext 
マージして本番環境に反映されていることを確認済みです。

**Comment by ftnext** [comment]
https://2021.pycon.jp/ 確認しました。
対応ありがとうございました！👏
