### ISSUE TITLE
表記修正: Py Con → PyCon

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#4]
該当箇所
https://github.com/pyconjp/pycon.jp.2021.teaser/blob/082f5ed0ec8d967144ad84e543be7354a17d6e47/nuxt.config.js#L10

以下で指摘した件です
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1615811052072700

**Comment by papi-tokei** [comment]
修正済みです。
ただ、このissuheはマスターマージ後にクローズします。

**Comment by papi-tokei** [comment]
@ftnext 
マスターにマージ済みです。
修正内容が問題なければ、このissueのクローズをお願いします。

**Comment by ftnext** [comment]
確認しました。
対応ありがとうございました
