### ISSUE TITLE
プロポーザル用のLatest Informationを追加したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#40]
2つ目のLatest Informationを追加して、2つのカードを左右に並べたいです。
完成形は、Slack #2021-website のトピックからfigmaを見てください

## 文面
「プロポーザル募集準備中」
以下で公開を進めているブログ記事にリンクしてください
https://pyconjp.slack.com/archives/C01FBPX83GD/p1620996898417200

このIssueの外の作業として、
プロポーザルが公開されたらリンクを差し替える想定です

**Comment by try46** [comment]
#41 と一緒に対応したです、stg環境でご確認を
