### ISSUE TITLE
スポンサーシップ用のLatest Informationを追加したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#41]
2つ目（#40 を先にやる場合は3つ目） のLatest Informationを追加して、カードを（上下）左右に並べたいです。
完成形は、Slack #2021-website のトピックからfigmaを見てください

## 文面
「スポンサー募集準備中」
（5/26時点では）以下で公開を進めているブログ記事にリンクしてください
https://pyconjp.blogspot.com/2021/05/pycon-jp-2021.html

このIssueの外の作業として、
5/31にスポンサーシップ1次募集が開始されたらリンクを差し替える想定です

**Comment by try46** [comment]
既に本番環境に反映されているのを確認したのでクローズします。
