### ISSUE TITLE
ヘッダーのCode of Conductのリンク先を変更したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#42]
変更先
https://drive.google.com/file/d/1iNF7VvDCd_gWDsSn2i5U8FB1IQWkWOM9/view?usp=sharing

**Comment by papi-tokei** [comment]
@ftnext 
修正済み、本番環境へ反映済みです。

**Comment by ftnext** [comment]
スマホで確認しました。
対応ありがとうございます
