### ISSUE TITLE
ヘッダーのSPONSORからスポンサー募集開始ブログにリンクしたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#49]
https://pyconjp.blogspot.com/2021/05/pycon-jp-2021_01988973482.html へのリンクにしてください

**Comment by papi-tokei** [comment]
@ftnext 
修正済み、本番環境へ反映済みです。

**Comment by ftnext** [comment]
スマホで確認しました。
対応ありがとうございます
