### ISSUE TITLE
ヘッダーにTwitterアイコンを表示したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#5]
位置：ヘッダーのFaceBookアイコンの隣
内容：Twitterアイコン。https://twitter.com/pyconjapan へのリンク

デザインについてはこちらでお願いしているので、参照して進めてください
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1616070213020100

**Comment by papi-tokei** [comment]
修正済みです。マスターマージ後にクローズ予定です。

**Comment by papi-tokei** [comment]
@ftnext 
マスターにマージ済みです。
修正内容が問題なければ、このissueのクローズをお願いします。

**Comment by ftnext** [comment]
確認しました。
対応ありがとうございます
