### ISSUE TITLE
スポンサーシップのLatest Informationから募集開始ブログにリンクしたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#50]
https://pyconjp.blogspot.com/2021/05/pycon-jp-2021_01988973482.html へのリンクにしてください

スポンサーシップのLatest Informationはdevelopブランチには取り込まれているため、着手可能の認識です（ステージング環境で見えています）

最新の状況
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1622390244077800?thread_ts=1622038211.017500&cid=C01M5K8JKKN

**Comment by papi-tokei** [comment]
@ftnext 
修正済み、本番環境へ反映済みです。

**Comment by ftnext** [comment]
スマホで確認しました。
対応ありがとうございます
