### ISSUE TITLE
ヘッダーのPROPOSALからプロポーザル募集開始ブログにリンクしたい

### ISSUE THREAD

**Issue by masamori0083** [pyconjp/pycon.jp.2021.teaser#52]
https://pyconjp.blogspot.com/2021/05/start-proposal.html にリンクお願いします。

**Comment by papi-tokei** [comment]
@masamori0083 
修正済み、本番環境へ反映済みです。

**Comment by ftnext** [comment]
スマホで確認しました。
対応ありがとうございます

@masamori0083 確認してよさそうでしたらクローズお願いします

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue, please point me the files, I'll do rest.

**Comment by ftnext** [comment]
This issue was already fixed by https://github.com/pyconjp/pycon.jp.2021.teaser/commit/b5f04720727dd2163d8a35134e8eaf825c74b0e3.

This issue will be closed soon after the issue author checks the site https://2021.pycon.jp/.
