### ISSUE TITLE
プロポーザル募集のLatest Informationから募集開始ブログにリンクしたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021.teaser#53]
https://pyconjp.blogspot.com/2021/05/start-proposal.html へのリンクに切り替えお願いします

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue, please guide me to the file where this link needs to be changed

**Comment by ftnext** [comment]
Thanks to @try46, this issue was fixed🎉
https://github.com/pyconjp/pycon.jp.2021.teaser/commit/ad496b2ea1c0bb306467352f4df49eeb51f62d4d

We can see the site at https://2021.pycon.jp/ and the proposal button is working.

**Comment by ftnext** [comment]
@himanshu007-creator Thank you for your interest. 
We are looking forward to working with you next time.
